### ISSUE TITLE
docker:publishLocal failed for me

### ISSUE THREAD

**Issue by gzoller** [mhamrah/akka-docker-cluster-example#1]
Hello,

Followed directions and in sbt did docker:publishLocal.  Got the error below:

> docker:publishLocal
> [info] Packaging /Users/Greg/git/akka-docker-cluster-example/target/scala-2.11/clustering_2.11-0.3-sources.jar ...
> [info] Done packaging.
> [info] Wrote /Users/Greg/git/akka-docker-cluster-example/target/scala-2.11/clustering_2.11-0.3.pom
> [info] Main Scala API documentation to /Users/Greg/git/akka-docker-cluster-example/target/scala-2.11/api...
> [info] Packaging /Users/Greg/git/akka-docker-cluster-example/target/scala-2.11/clustering_2.11-0.3.jar ...
> [info] Done packaging.
> model contains 7 documentable templates
> [info] Main Scala API documentation successful.
> [info] Packaging /Users/Greg/git/akka-docker-cluster-example/target/scala-2.11/clustering_2.11-0.3-javadoc.jar ...
> [info] Done packaging.
> [info] Step 0 : FROM dockerfile/java:latest
> [info] Pulling repository dockerfile/java
> [error] 2015/05/06 14:04:42 Error: image dockerfile/java not found
> [trace] Stack trace suppressed: run last docker:publishLocal for the full output.
> [error](docker:publishLocal) Nonzero exit value: 1
> [error] Total time: 5 s, completed May 6, 2015 7:04:42 PM

**Comment by mhamrah** [comment]
This is fairly old repo which I need to update. Docker deprecated the
dockerfile project, and now it's just "java" instead of "dockerfile/java".
You can try changing the base image to get it to work- i'll try and push an
update shortly.
